import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import SelectDashBoard from './components/dashBoard/selectDashBoard';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='relative flex flex-col md:flex-row bg-white w-screen'
      >
    <SelectDashBoard />
        {children}
        </body>
    </html>
  );
}
